### ISSUE TITLE
opx-snmp: service dies if prtg searches for available snmp data

### ISSUE THREAD

**Issue by disaster123** [open-switch/opx-snmp#10]
journal show the following error
```
Oct 01 19:32:00 r3 SNMPAgent[10224]: SNMPAgent: version is v2
Oct 01 19:32:00 r3 SNMPAgent[10224]: Starting agent
Oct 01 19:32:00 r3 SNMPAgent[10224]: Traceback (most recent call last):
Oct 01 19:32:00 r3 SNMPAgent[10224]:   File "/usr/sbin/SNMPAgent", line 293, in <module>
Oct 01 19:32:00 r3 SNMPAgent[10224]:     agent.serve_forever()
Oct 01 19:32:00 r3 SNMPAgent[10224]:   File "/usr/sbin/SNMPAgent", line 284, in serve_forever
Oct 01 19:32:00 r3 SNMPAgent[10224]:     self._snmpEngine.transportDispatcher.runDispatcher()
Oct 01 19:32:00 r3 SNMPAgent[10224]:   File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dispatch.py", line 50, in runDispatcher
Oct 01 19:32:00 r3 SNMPAgent[10224]:     raise PySnmpError('poll error: %s' % ';'.join(format_exception(*exc_info())))
Oct 01 19:32:00 r3 SNMPAgent[10224]: pysnmp.error.PySnmpError: poll error: Traceback (most recent call last):
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dispatch.py", line 46, in runDispatcher
Oct 01 19:32:00 r3 SNMPAgent[10224]:     use_poll=True, map=self.__sockMap, count=1)
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/lib/python2.7/asyncore.py", line 220, in loop
Oct 01 19:32:00 r3 SNMPAgent[10224]:     poll_fun(timeout, map)
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/lib/python2.7/asyncore.py", line 201, in poll2
Oct 01 19:32:00 r3 SNMPAgent[10224]:     readwrite(obj, flags)
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/lib/python2.7/asyncore.py", line 123, in readwrite
Oct 01 19:32:00 r3 SNMPAgent[10224]:     obj.handle_error()
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/lib/python2.7/asyncore.py", line 108, in readwrite
Oct 01 19:32:00 r3 SNMPAgent[10224]:     obj.handle_read_event()
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/lib/python2.7/asyncore.py", line 449, in handle_read_event
Oct 01 19:32:00 r3 SNMPAgent[10224]:     self.handle_read()
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/asyncore/dgram/base.py", line 170, in handle_read
Oct 01 19:32:00 r3 SNMPAgent[10224]:     self._cbFun(self, transportAddress, incomingMessage)
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/carrier/base.py", line 70, in _cbFun
Oct 01 19:32:00 r3 SNMPAgent[10224]:     self, transportDomain, transportAddress, incomingMessage
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/entity/engine.py", line 152, in __receiveMessageCbFun
Oct 01 19:32:00 r3 SNMPAgent[10224]:     self, transportDomain, transportAddress, wholeMsg
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/proto/rfc3412.py", line 433, in receiveMessage
Oct 01 19:32:00 r3 SNMPAgent[10224]:     PDU, maxSizeResponseScopedPDU, stateReference)
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/entity/rfc3413/cmdrsp.py", line 161, in processPdu
Oct 01 19:32:00 r3 SNMPAgent[10224]:     errorStatus, errorIndex = 'noSuchName', sys.exc_info()[1]['idx'] + 1
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;  File "/usr/local/lib/python2.7/dist-packages/pysnmp/smi/error.py", line 31, in __getitem__
Oct 01 19:32:00 r3 SNMPAgent[10224]:     return self.__outArgs[key]
Oct 01 19:32:00 r3 SNMPAgent[10224]: ;KeyError: 'idx'
Oct 01 19:32:00 r3 SNMPAgent[10224]: caused by <type 'exceptions.KeyError'>: 'idx'
Oct 01 19:32:00 r3 systemd[1]: opx-pysnmp.service: Main process exited, code=exited, status=1/FAILURE
Oct 01 19:32:00 r3 systemd[1]: opx-pysnmp.service: Unit entered failed state.
Oct 01 19:32:00 r3 systemd[1]: opx-pysnmp.service: Failed with result 'exit-code'.
```

**Comment by disaster123** [comment]
@atanu-mandal  any news on this?

**Comment by GildedHonour** [comment]
Is help needed on this and on #11?

**Comment by mikelazar** [comment]
@GildedHonour Hi Alex, yes we'd some help with this. Would you be available ?

**Comment by GildedHonour** [comment]
Yes. Tomorrow. 

@disaster123 or @mikelazar, where to can I send you a message first? I don't know who is who.

**Comment by disaster123** [comment]
don't wanna post a mail address here - should i sent one to your email adress on your profile?

**Comment by GildedHonour** [comment]
@disaster123 yes.

**Comment by disaster123** [comment]
@GildedHonour i'm a bit confused what do you mean by you don't know who is who? Are you from Dell? @mikelazar is from Dell. I'm just a "stupid" user of OPX.

**Comment by GildedHonour** [comment]
@disaster123 I'm not, I'm a solo developer.

**Comment by gunasekaran-t** [comment]
@disaster123 could you please share info on how to recreate the issue. Please share the platform and OID detail that was queried.

**Comment by disaster123** [comment]
Not much I was just trying to add the switch to https://www.paessler.com/prtg device was s4248fbl
